### PR TITLE
reorganize io namespace

### PR DESCRIPTION
**Pull request by pchalamet**
Cleanup IO namespace - Exec, IoHelpers was a mixed bag.

Now:
- IO : io result & operations
- Exec : Process exec & co
- ConHelpers : Console io
- FsHelpers : FS operations

### CODE REVIEW

**Comment by sergii-s** [comment]
ConHelpers and ConsHelpers not the same thing 😄

**Comment by sergii-s** [comment]
You can simpy call it Console and it will behave like extension

**Comment by pchalamet** [comment]
Didn't know that :-) ok will check
But they are just helpers and not really extensions btw - just sugar around console outputs

**Comment by pchalamet** [comment]
Renaming to Console does work - but for FsHelpers this introduce a lot of name clashes..
Not that excited in fact...

**Comment by sergii-s** [comment]
Can you rename it to ConsoleHelpers at least? ConHelpers not intuitive

**Comment by pchalamet** [comment]
ok done

**Pull request merged**
